class_name NINFA_GUI

enum STATES {MAIN_MENU, GAME, INGAME_MENU, TRANSITIONING}
enum ACTIONS {
    START_GAME, 
    REVEAL_INGAME_MENU, 
    HIDE_INGAME_MENU, 
    RETURN_TO_MAIN_MENU, 
    EXIT_TO_SYSTEM
}
